Added Droplet Deletion
coding-blocks/DigitalOceanApp pull request #45
Opened 2017-06-10 20:43 UTC by ojasvajain

I have implemented Droplet Deletion Functionality. One thing I want to mention is when I receive the response code on deleting the droplet, and if I immediately refresh the list of Droplets in `DropletActivity` using `DropletActivity.refreshData()`, I get the deleted droplet as well in the list. Therefore I am refreshing after a duration of 5 secs, in which case its working fine. Need your suggestion on whether this can handled more sophistically.   
![ezgif-1-4ba5a9730b](https://user-images.githubusercontent.com/18742006/27006186-7757bcba-4e4b-11e7-800a-94fc7ede3ccf.gif)

2017-06-13 18:57 UTC, ojasvajain commented
Please review PR

2017-06-23 20:50 UTC, the-dagger requested changes

2017-06-23 20:50 UTC, the-dagger commented on app/src/main/java/in/tosc/digitaloceanapp/activities/DetailDropletActivity.java
> +                            }, 5000);
Why are you hardcoding the time over here?

2017-06-24 06:54 UTC, the-dagger requested changes

2017-06-24 06:54 UTC, the-dagger commented on app/src/main/java/in/tosc/digitaloceanapp/activities/DetailDropletActivity.java
> +                            },getResources().getInteger(R.integer.REFRESH_AFTER_DELETE_TIMEOUT));
No, what I meant was, why are you waiting for a fixed time, you should only wait for the time which is actually taken while deleting this droplet.

2017-06-29 09:47 UTC, merged