Fixed Issue #47 : Package name starts with lower case
coding-blocks/DigitalOceanApp pull request #49
Opened 2017-06-22 13:08 UTC by ojasvajain

2017-06-22 16:28 UTC, the-dagger requested changes

2017-06-22 16:28 UTC, the-dagger commented on app/src/main/java/in/tosc/digitaloceanapp/interfaces/onDropletNameChange.java
Please also rename the class inside it to `OnDropletNameChange.java`

2017-06-22 16:55 UTC, ojasvajain commented on app/src/main/java/in/tosc/digitaloceanapp/interfaces/onDropletNameChange.java
Done

2017-06-23 20:48 UTC, the-dagger approved these changes

2017-06-23 20:48 UTC, merged