Deleting a droplet
coding-blocks/DigitalOceanApp pull request #8
Opened 2017-05-15 06:36 UTC by Pritom14

2017-05-15 07:06 UTC, championswimmer requested changes

2017-05-15 07:06 UTC, championswimmer commented on app/src/main/java/in/tosc/digitaloceanapp/activities/DetailDropletActivity.java
> +                            Log.d("DESTROY",response.code()+"");
Do not convert to string like this 
Use explicit typecast like String.valueOf

2017-05-15 07:25 UTC, Pritom14 commented on app/src/main/java/in/tosc/digitaloceanapp/activities/DetailDropletActivity.java
> +                            Log.d("DESTROY",response.code()+"");
Okay, but can you please elaborate the changes I have to make, as to where should I use String.valueOf?

2017-05-15 08:24 UTC, Pritom14 commented
Please review the PR

2017-05-16 11:53 UTC, championswimmer requested changes

2017-05-16 11:53 UTC, championswimmer commented on app/src/main/java/in/tosc/digitaloceanapp/activities/DetailDropletActivity.java
> +                    .content("")
Add some information
(Maybe some warning like - "This action is not reversible" in the content

2017-05-16 15:01 UTC, closed without merging